In [2]:
from qiskit import __version__ as qiskit_version

print(f"Qiskit version: {qiskit_version}")

Qiskit version: 2.2.3


In [3]:
from qiskit.quantum_info import Statevector
from numpy import sqrt

u = Statevector([1/sqrt(2), 1/sqrt(2)])
v = Statevector([(1+2j)/3, -2/3])
w = Statevector([1/3, 2/3])

In [2]:
import numpy as np

In [3]:
ket0 = np.array([[1], [0]])
ket1 = np.array([[0], [1]])

print(ket0/2 + ket1/2)

[[0.5]
 [0.5]]


In [4]:
M1 = np.array([[1,1], [0,0]])
M2 = np.array([[1,0], [0,1]])
M = M1/2 + M2/2

print(f"M: {M}")


M: [[1.  0.5]
 [0.  0.5]]


In [8]:
# multiplication
print(np.matmul(M1, ket1))
print(np.matmul(M1, M2))
print(np.matmul(M, M))

[[1]
 [0]]
[[1 1]
 [0 0]]
[[1.   0.75]
 [0.   0.25]]


In [10]:
from qiskit.visualization import array_to_latex

display(array_to_latex(np.matmul(M1, ket1)))
display(array_to_latex(np.matmul(M1, M2)))
display(array_to_latex(np.matmul(M, M)))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [2]:
from qiskit.quantum_info import Statevector
from numpy import sqrt

u = Statevector([1/sqrt(2), 1/sqrt(2)])
v = Statevector([(1 + 2j)/3, -2/3])
w = Statevector([1/3, 2/3])

In [16]:
display(u.draw("text"))
display(u.draw("latex"))
display(v.draw("text"))
display(v.draw("latex"))

[0.70710678+0.j,0.70710678+0.j]

<IPython.core.display.Latex object>

[ 0.33333333+0.66666667j,-0.66666667+0.j        ]

<IPython.core.display.Latex object>

In [15]:
# check state vector
display(u.is_valid())
display(v.is_valid())

True

True