**Input**: Two matrices

**Goal**: Return the sum of two matrices

In [2]:
import numpy as np
def add_matrices(matrix1,matrix2):
  try:
    return np.add(matrix1, matrix2)
  except ValueError as e:
    return f"An error: {e}"

matrix1 = np.array([
  [1,2,5,6],
  [8,7,323,6],
  [134,2154,2,63],
])

matrix2 = np.array([
  [13,23,53,36],
  [83,73,323,6],
  [1343,23154,23,633],
])

print(add_matrices(matrix1, matrix2))

[[   14    25    58    42]
 [   91    80   646    12]
 [ 1477 25308    25   696]]
