**Input**: 
1. A number

2. A matrix

**Goal**: Return the result of multiplying the following matrix by the scalar

In [1]:
import numpy as np
def scalar_multiplication(r: float, arr):
  matrix=np.array(arr)
  return r*matrix

print(scalar_multiplication(10, [[1,3,3,5],[2,3,6,3],[523,32,2,34]]))

[[  10   30   30   50]
 [  20   30   60   30]
 [5230  320   20  340]]
