**Input**: Two matrixes

**Goal**: Return the tensor product of the following matrixes

In [2]:
import numpy as np
def tensor_product(matrix_A, matrix_B):
  np_matrix_A = np.array(matrix_A)
  np_matrix_B = np.array(matrix_B)
  
  return np.kron(np_matrix_A, np_matrix_B)

print(tensor_product([[1,2],[3,4]], [[5,6],[7,8]]))
print(tensor_product([[1,2j],[3,4+3j]], [[5,6],[7,8]]))

[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]
[[ 5. +0.j  6. +0.j  0.+10.j  0.+12.j]
 [ 7. +0.j  8. +0.j  0.+14.j  0.+16.j]
 [15. +0.j 18. +0.j 20.+15.j 24.+18.j]
 [21. +0.j 24. +0.j 28.+21.j 32.+24.j]]
